import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import {
  BytecodeCaptureError,
  captureBytecode,
  parseBytecodeListing,
  selectUserBytecode,
} from "../../scripts/conformance/bytecode-capture.mts";
import { parseExpectation, type RealFunctionBytecode } from "../../scripts/conformance/expectation.mts";
import { checkPinnedRuntime, readTarget } from "../../scripts/conformance/target.mts";

// listing.sample.txt is an unedited excerpt of a real `--print-bytecode` run on the
// pinned Node (through scripts/conformance/mark.cjs) of this program:
//
//   q = 1;
//   function j(a,z){let s=0;s=a;s=s+a;s=s+a;s=s+a;s=s+a;s=s+a;s=s+a;return a===1||z()}
//   function f(a){return a}
//   function t(){try{return f(1)}catch(e){return 0}}
//   console.log(q,j(2,f),t());
//
// It starts at mark.cjs's own wrapper (so it holds a Node-side `Parameter count 6`
// block BEFORE the marker) and ends after the first internal block that follows t.
const sample = readFileSync(join(import.meta.dirname, "support", "listing.sample.txt"), "utf8");

const names = (b: RealFunctionBytecode): string[] => [b.name, ...Object.values(b.children).flatMap(names)];

describe("parseBytecodeListing (pure)", () => {
  const blocks = parseBytecodeListing(sample);
  const byName = (name: string) => {
    const found = blocks.filter((b) => b.name === name);
    expect(found).toHaveLength(1);
    return found[0]!;
  };

  it("splits every block, in listing order", () => {
    expect(blocks).toHaveLength(15);
    expect(blocks.map((b) => b.name).slice(-6)).toEqual(["", "", "j", "f", "t", ""]);
  });

  it("reads the header numbers", () => {
    expect(byName("j").header).toEqual({ length: 52, parameterCount: 3, registerCount: 1, frameSize: 8 });
    expect(byName("t").header).toEqual({ length: 27, parameterCount: 1, registerCount: 3, frameSize: 24 });
  });

  it("strips addresses and hex bytes from instructions, keeping offsets and positions", () => {
    expect(byName("f").instructions).toEqual([
      { offset: 0, position: { at: 104, kind: "S" }, text: "Ldar a0" },
      { offset: 2, position: { at: 112, kind: "S" }, text: "Return" },
    ]);
    const j = byName("j").instructions;
    expect(j[0]).toEqual({ offset: 0, position: { at: 29, kind: "S" }, text: "LdaZero" });
    expect(j[1]).toEqual({ offset: 1, text: "Star0" });
    expect(j.find((i) => i.offset === 37)).toEqual({ offset: 37, position: { at: 68, kind: "E" }, text: "Add r0, [5]" });
  });

  it("prints a jump target as (@offset)", () => {
    expect(byName("j").instructions.find((i) => i.offset === 46)).toEqual({ offset: 46, text: "JumpIfTrue [5] (@51)" });
  });

  it("keeps operands such as <context> and register lists", () => {
    expect(byName("t").instructions[0]).toEqual({ offset: 0, text: "Mov <context>, r0" });
    const root = blocks.find((b, i) => b.header.parameterCount === 6 && i > blocks.findIndex((x) => x.name === "__silicon_marker__"));
    expect(root?.instructions.map((i) => i.text)).toContain("CallProperty r3, r4-r7, [12]");
  });

  it("strips addresses from constant-pool entries but remembers SFI addresses", () => {
    const root = blocks[10]!;
    expect(root.header.parameterCount).toBe(6);
    expect(root.constantPool.map((c) => c.text)).toEqual([
      "<ScopeInfo FUNCTION_SCOPE>",
      "<SharedFunctionInfo j>",
      "<SharedFunctionInfo f>",
      "<SharedFunctionInfo t>",
      "<String[1]: #q>",
      "<String[7]: #console>",
      "<String[3]: #log>",
    ]);
    expect(root.constantPool[1]?.sfi).toBe(byName("j").sfi);
    expect(root.constantPool[0]?.sfi).toBeUndefined();
    expect(byName("j").constantPool).toEqual([]);
  });

  it("reads handler-table entries", () => {
    expect(byName("t").handlerTable).toEqual(["(3, 14) -> 14 (prediction=1, data=0)"]);
    expect(byName("j").handlerTable).toEqual([]);
  });

  it("expands a constant-pool range entry into one entry per index", () => {
    const listing = [
      "[generated bytecode for function: r (0x0000000000a1 <SharedFunctionInfo r>)]",
      "Bytecode length: 1",
      "Parameter count 1",
      "Register count 0",
      "Frame size 0",
      "         0000000000000001 @    0 : b3                Return",
      "Constant pool (size = 4)",
      "0000000000000002: [TrustedFixedArray]",
      " - map: 0x000000000003 <Map(TRUSTED_FIXED_ARRAY_TYPE)>",
      " - length: 4",
      "           0: 7",
      "         1-3: 0x000000000004 <Odd Oddball: uninitialized>",
      "Handler Table (size = 0)",
      "Source Position Table (size = 0)",
    ].join("\r\n");
    const [r] = parseBytecodeListing(listing);
    expect(r?.constantPool.map((c) => c.text)).toEqual(["7", ...Array(3).fill("<Odd Oddball: uninitialized>")]);
  });

  it("fails loudly on a malformed block instead of skipping it", () => {
    const broken = sample.replace("Register count 3", "Register count three");
    expect(() => parseBytecodeListing(broken)).toThrow(BytecodeCaptureError);
    const garbled = sample.replace("@   46 : a2 05", "@ 46 a2 05");
    expect(() => parseBytecodeListing(garbled)).toThrow(/line \d+/);
  });
});

describe("selectUserBytecode (pure)", () => {
  it("roots at the first Parameter count 6 block after the marker and walks SFI addresses", () => {
    const root = selectUserBytecode(parseBytecodeListing(sample));
    expect(root.name).toBe("");
    expect(root.header.parameterCount).toBe(6);
    expect(Object.keys(root.children)).toEqual(["1", "2", "3"]);
    expect(root.children["1"]?.name).toBe("j");
    expect(root.children["2"]?.name).toBe("f");
    expect(root.children["3"]?.name).toBe("t");
    expect(root.constantPool[1]).toBe("<SharedFunctionInfo j>");
    expect(names(root).sort()).toEqual(["", "f", "j", "t"]);
  });

  it("re-anchors positions inside text Node appended after the program (.cts sourceURL)", () => {
    const blocks = parseBytecodeListing(sample);
    // The sample's wrapper Return sits at 190, the program's length: nothing appended.
    expect(selectUserBytecode(blocks, 190)).toEqual(selectUserBytecode(blocks));
    // Pretend the program was 186 characters and Node appended 4: only positions
    // at or past 186 move, back by 4, so the implicit return lands at 185.
    const shifted = selectUserBytecode(blocks, 186);
    const plain = selectUserBytecode(blocks);
    expect(shifted.instructions.at(-1)).toEqual({ offset: 61, position: { at: 185, kind: "S" }, text: "Return" });
    expect(shifted.instructions.slice(0, -1)).toEqual(plain.instructions.slice(0, -1));
    expect(shifted.children).toEqual(plain.children);
    expect(() => selectUserBytecode(blocks, 191)).toThrow(/wrapper ends at 190/);
  });

  it("throws when the marker is missing", () => {
    const blocks = parseBytecodeListing(sample).filter((b) => b.name !== "__silicon_marker__");
    expect(() => selectUserBytecode(blocks)).toThrow(/marker/);
  });

  it("throws when a child SFI address is compiled twice (ambiguous walk)", () => {
    const blocks = parseBytecodeListing(sample);
    const f = blocks.find((b) => b.name === "f")!;
    expect(() => selectUserBytecode([...blocks, f])).toThrow(/more than once/);
  });

  it("throws when the block at a child address is a different function (address reuse)", () => {
    const blocks = parseBytecodeListing(sample).map((b) =>
      b.name === "f" ? { ...b, name: "other", descriptor: "<SharedFunctionInfo other>" } : b,
    );
    expect(() => selectUserBytecode(blocks)).toThrow(/expected <SharedFunctionInfo f>/);
  });
});

describe("captureBytecode against the recorded outcome (injected run)", () => {
  // The sample's main script is 190 characters long; the text itself is never parsed here.
  const source = "x".repeat(190);
  const fakeRun = (exitCode: number) => () => ({ stdout: sample, stderr: "boom", exitCode });

  it("returns the tree when the capture run exits like the recorded run", () => {
    const tree = captureBytecode(source, "js", { expectedExitCodes: [0], run: fakeRun(0) });
    expect(tree).toEqual(selectUserBytecode(parseBytecodeListing(sample)));
  });

  it("throws when the capture run exits differently, even though the listing parses", () => {
    // The root is compiled before anything can go wrong, so a run that died early
    // still yields a tree; only the exit code shows its children may be missing.
    expect(() => captureBytecode(source, "js", { expectedExitCodes: [0], run: fakeRun(134) })).toThrow(
      expect.objectContaining({ name: "BytecodeCaptureError", message: expect.stringMatching(/exited with 134.*recorded run\(s\) exited with 0.*boom/) }),
    );
  });

  it("accepts any exit code a nondeterministic fixture recorded", () => {
    expect(() => captureBytecode(source, "js", { expectedExitCodes: [0, 1], run: fakeRun(1) })).not.toThrow();
  });
});

// Spawning real node is only meaningful on the pinned runtime (docs/TARGET.md).
const pinnedProblems = checkPinnedRuntime({ node: process.versions.node, v8: process.versions.v8 }, readTarget());
const pinned = pinnedProblems.length === 0;
if (!pinned) {
  console.warn(`Skipping real bytecode capture tests: ${pinnedProblems.join("; ")} (docs/TARGET.md)`);
}

describe.skipIf(!pinned)("captureBytecode (real node)", () => {
  const program = "function f(a){return a}\nconst g=x=>x+1;\nconsole.log(f(1),g(2));";

  it("captures the main script and exactly the user functions it called", () => {
    const root = captureBytecode(program, "js");
    expect(root.header.parameterCount).toBe(6);
    const fIndex = root.constantPool.indexOf("<SharedFunctionInfo f>");
    const gIndex = root.constantPool.indexOf("<SharedFunctionInfo g>");
    expect(fIndex).toBeGreaterThanOrEqual(0);
    expect(gIndex).toBeGreaterThanOrEqual(0);
    expect(Object.keys(root.children).sort()).toEqual([String(fIndex), String(gIndex)].sort());
    expect(root.children[String(fIndex)]?.instructions.map((i) => i.text)).toEqual(["Ldar a0", "Return"]);
    expect(root.children[String(gIndex)]?.name).toBe("g");
    // No Node internal (mark.cjs, the loader, console) leaks into the tree.
    expect(names(root).sort()).toEqual(["", "f", "g"]);
  });

  it("leaves out a function that was never called", () => {
    const root = captureBytecode(
      "function f(a){return a}\nconst never=function never(){return 1};\nconsole.log(f(1),typeof never);",
      "js",
    );
    expect(root.constantPool).toContain("<SharedFunctionInfo never>");
    expect(names(root).sort()).toEqual(["", "f"]);
  });

  it("captures nested functions under their parent", () => {
    const root = captureBytecode("function outer(){function inner(){return 1}return inner()}\nconsole.log(outer());", "js");
    const outer = Object.values(root.children)[0];
    expect(outer?.name).toBe("outer");
    expect(Object.values(outer?.children ?? {}).map((c) => c.name)).toEqual(["inner"]);
  });

  it("yields the identical tree for the same program as .cts with type annotations", () => {
    const ts = "function f(a: number): number {return a}\nconst g=(x: number)=>x+1;\nconsole.log(f(1),g(2));";
    // Type stripping blanks annotations to spaces, so the matching JS keeps every offset.
    // Node also appends `//# sourceURL=<temp path>` to a .cts; without re-anchoring,
    // the root's implicit Return position would differ (it did: 175 vs 89).
    const js = ts.replace(/: number/g, "        ");
    expect(js.length).toBe(ts.length);
    expect(captureBytecode(ts, "ts")).toEqual(captureBytecode(js, "js"));
  });

  it("throws BytecodeCaptureError when the program never reaches its main script", () => {
    expect(() => captureBytecode("function (", "js")).toThrow(BytecodeCaptureError);
  });

  it("throws when the real capture run ends differently from the recorded outcome", () => {
    // Recorded as exiting 0, but this program throws after f's call: g is never compiled.
    const diverging = "function f(a){return a}\nfunction g(){return 2}\nf(1);\nthrow new Error('x');\ng();";
    expect(() => captureBytecode(diverging, "js", { expectedExitCodes: [0] })).toThrow(/exited with 1/);
    expect(names(captureBytecode(diverging, "js", { expectedExitCodes: [1] })).sort()).toEqual(["", "f"]);
  });

  it("produces a tree the expectation schema accepts", () => {
    const bytecode = captureBytecode("try{console.log([1].map(x=>x))}catch(e){}", "js");
    const expectation = {
      schema: 1,
      fixture: "a",
      kind: "program",
      lang: "js",
      target: readTarget(),
      nondeterministic: false,
      outcomes: [{ stdout: "[ 1 ]\n", stderr: "", exitCode: 0 }],
      bytecode,
    };
    expect(parseExpectation(expectation).bytecode).toEqual(bytecode);
    expect(bytecode.handlerTable).toHaveLength(1);
  });
});
