import { fileURLToPath } from "node:url";
import type { RealFunctionBytecode, RealInstruction, RunFn } from "./expectation.mts";
import { runReal } from "./run-real.mts";

// Real Ignition bytecode for the user functions of a repo-owned fixture program,
// read from `node --print-bytecode` (docs/FIDELITY.md, "Ignition bytecode listing").
//
// The listing holds every function V8 compiled, ~100 of them Node internals, in
// compile order. To find the user's, mark.cjs is preloaded: it calls
// `__silicon_marker__` just before Node compiles main.cjs/main.cts, so the first
// `Parameter count 6` block after the marker is the main script (CJS compiles it
// as `function (exports, require, module, __filename, __dirname)`, 5 parameters
// plus the receiver). From there children are found by SharedFunctionInfo
// address: a parent's constant pool lists `0xADDR <SharedFunctionInfo f>`, and
// f's own block header carries the same address. A function V8 never compiled
// (never called) has no block and is left out.
//
// Every surprise throws BytecodeCaptureError: a capture is never silently partial.

export class BytecodeCaptureError extends Error {
  override name = "BytecodeCaptureError";
}

export type RawConstant = {
  /** The entry with heap addresses stripped, e.g. `<SharedFunctionInfo f>`, `<String[7]: #console>`, `7`. */
  readonly text: string;
  /** The SharedFunctionInfo address, only for SFI entries. */
  readonly sfi?: string;
};

export type RawBlock = {
  readonly name: string;
  /** Address of this function's SharedFunctionInfo, as printed (`0x…`). */
  readonly sfi: string;
  /** `<SharedFunctionInfo NAME>`, the same text a parent's constant pool shows. */
  readonly descriptor: string;
  readonly header: RealFunctionBytecode["header"];
  readonly instructions: RealInstruction[];
  readonly constantPool: RawConstant[];
  readonly handlerTable: string[];
};

// V8 BytecodeArray::Disassemble (src/objects/bytecode-array.cc).
const BLOCK_RE = /\[generated bytecode for function: (.*) \((0x[0-9a-fA-F]+) (<SharedFunctionInfo.*>)\)\]$/;
const LENGTH_RE = /^Bytecode length: (\d+)$/;
const PARAMS_RE = /^Parameter count (\d+)$/;
const REGISTERS_RE = /^Register count (\d+)$/;
const FRAME_RE = /^Frame size (\d+)$/;
// `  POS S|E> ADDR @ OFFSET : HEXBYTES  Mnemonic operands`; hex bytes are lowercase
// pairs, a mnemonic starts with an upper-case letter.
const INSTRUCTION_RE = /^\s*(?:(\d+) ([SE])> )?\s*(?:0x)?[0-9A-Fa-f]+ @\s*(\d+) : (?:[0-9a-f]{2} )+\s*([A-Z].*?)\s*$/;
const JUMP_TARGET_RE = /\((?:0x)?[0-9A-Fa-f]+ @ (\d+)\)/g;
const POOL_RE = /^Constant pool \(size = (\d+)\)$/;
const POOL_ENTRY_RE = /^\s+(\d+)(?:-(\d+))?: (.*)$/;
const POOL_PREAMBLE_RE = /^(?:(?:0x)?[0-9A-Fa-f]+: \[\w*FixedArray\]| - map: .*| - length: \d+)$/;
// A heap address in front of a printed object: `0x0213004122a9 <...>`.
const ADDRESS_RE = /0x[0-9a-fA-F]+ (?=<)/g;
const SFI_ENTRY_RE = /^(0x[0-9a-fA-F]+) <SharedFunctionInfo/;
const HANDLER_RE = /^Handler Table \(size = (\d+)\)$/;
const HANDLER_COLUMNS_RE = /^\s*from\s+to\s+hdlr/;
const HANDLER_ENTRY_RE = /^\s*\(\s*\d+,/;
const SOURCE_POSITIONS_RE = /^Source Position Table \(size = \d+\)$/;
// Each handler-table range entry is 4 int32s (src/codegen/handler-table.h).
const HANDLER_ENTRY_BYTES = 16;

/** Splits a `--print-bytecode` listing into blocks, addresses and hex bytes stripped. Pure. */
export function parseBytecodeListing(stdout: string): RawBlock[] {
  const lines = stdout.split(/\r?\n/);
  const blocks: RawBlock[] = [];
  let i = 0;
  const fail = (what: string): never => {
    throw new BytecodeCaptureError(`unexpected bytecode listing at line ${i + 1}: ${what}: ${JSON.stringify(lines[i] ?? "<end>")}`);
  };
  const next = (re: RegExp, what: string): RegExpMatchArray => {
    const m = (lines[i] ?? "").match(re);
    if (!m) return fail(`expected ${what}`);
    i++;
    return m;
  };
  const int = (m: RegExpMatchArray, group = 1) => Number(m[group]);

  while (i < lines.length) {
    const start = (lines[i] ?? "").match(BLOCK_RE);
    if (!start) {
      // Between blocks: the program's own output and V8's trailing address lines.
      i++;
      continue;
    }
    i++;
    const header = {
      length: int(next(LENGTH_RE, "Bytecode length")),
      parameterCount: int(next(PARAMS_RE, "Parameter count")),
      registerCount: int(next(REGISTERS_RE, "Register count")),
      frameSize: int(next(FRAME_RE, "Frame size")),
    };

    const instructions: RealInstruction[] = [];
    while (!POOL_RE.test(lines[i] ?? "")) {
      const m = next(INSTRUCTION_RE, "an instruction or Constant pool");
      const text = (m[4] ?? "").replace(JUMP_TARGET_RE, "(@$1)");
      const offset = int(m, 3);
      instructions.push(m[1] === undefined ? { offset, text } : { offset, position: { at: int(m), kind: m[2] === "S" ? "S" : "E" }, text });
    }

    const poolSize = int(next(POOL_RE, "Constant pool"));
    const constantPool: RawConstant[] = [];
    while (constantPool.length < poolSize) {
      if (POOL_PREAMBLE_RE.test(lines[i] ?? "")) {
        i++;
        continue;
      }
      const m = next(POOL_ENTRY_RE, "a constant-pool entry");
      const from = int(m);
      const to = m[2] === undefined ? from : int(m, 2);
      if (from !== constantPool.length || to < from) fail(`constant-pool index ${from} out of order`);
      const raw = m[3] ?? "";
      const sfi = raw.match(SFI_ENTRY_RE)?.[1];
      const entry: RawConstant = sfi === undefined ? { text: raw.replace(ADDRESS_RE, "") } : { text: raw.replace(ADDRESS_RE, ""), sfi };
      for (let k = from; k <= to; k++) constantPool.push(entry);
    }
    if (constantPool.length !== poolSize) fail(`constant pool overran its size ${poolSize}`);

    const handlerEntries = int(next(HANDLER_RE, "Handler Table")) / HANDLER_ENTRY_BYTES;
    const handlerTable: string[] = [];
    if (handlerEntries > 0) next(HANDLER_COLUMNS_RE, "the handler-table column header");
    while (HANDLER_ENTRY_RE.test(lines[i] ?? "")) {
      handlerTable.push((lines[i] ?? "").trim().replace(/\(\s+/g, "(").replace(/\s+/g, " "));
      i++;
    }
    if (handlerTable.length !== handlerEntries) fail(`expected ${handlerEntries} handler-table entries`);
    next(SOURCE_POSITIONS_RE, "Source Position Table");

    blocks.push({
      name: start[1] ?? "",
      sfi: (start[2] ?? "").toLowerCase(),
      descriptor: start[3] ?? "",
      header,
      instructions,
      constantPool,
      handlerTable,
    });
  }
  return blocks;
}

export const MARKER = "__silicon_marker__";
// 5 declared parameters of the CJS wrapper, plus the receiver.
const MAIN_PARAMETER_COUNT = 6;

/**
 * Picks the main script's block after the marker and walks its SFI tree. Pure.
 *
 * `scriptLength` is the length of the program text our model sees (BOM-less,
 * types stripped to whitespace). Node compiles a `.cts` with
 * `\n\n//# sourceURL=file:///<abs path>/main.cts` appended (verified on 24.19.0,
 * internal/modules/typescript stripTypeScriptModuleTypes), so the main script's
 * implicit-return position depends on the temp directory. The wrapper block's
 * Return sits at the end of the text V8 compiled, which gives the appended
 * length; positions inside the appended text are re-anchored to the end of the
 * program, which is exactly what V8 prints for the same text without the
 * suffix. A `.cjs` gets nothing appended, so this is a no-op there.
 */
export function selectUserBytecode(blocks: readonly RawBlock[], scriptLength?: number): RealFunctionBytecode {
  const marker = blocks.findIndex((b) => b.name === MARKER);
  if (marker < 0) throw new BytecodeCaptureError(`no ${MARKER} block: the preload did not run before the main script`);
  const after = blocks.slice(marker + 1);
  const rootIndex = after.findIndex((b) => b.header.parameterCount === MAIN_PARAMETER_COUNT);
  const root = after[rootIndex];
  if (root === undefined) throw new BytecodeCaptureError(`no Parameter count ${MAIN_PARAMETER_COUNT} block after ${MARKER}: the main script did not compile`);
  // V8 compiles the CJS wrapper as a 5-byte outer function whose only constant
  // is the main script's SFI; anything else means the listing changed shape.
  const wrapper = after[rootIndex - 1];
  if (wrapper?.constantPool.length !== 1 || wrapper.constantPool[0]?.sfi !== root.sfi) {
    throw new BytecodeCaptureError(`the Parameter count ${MAIN_PARAMETER_COUNT} block after ${MARKER} is not preceded by the main-script wrapper`);
  }
  let appended = 0;
  if (scriptLength !== undefined) {
    const compiledLength = wrapper.instructions.at(-1)?.position?.at;
    if (compiledLength === undefined || compiledLength < scriptLength) {
      throw new BytecodeCaptureError(`the main-script wrapper ends at ${compiledLength}, before the program's ${scriptLength} characters`);
    }
    appended = compiledLength - scriptLength;
  }
  const reanchor = (i: RealInstruction): RealInstruction =>
    i.position === undefined || i.position.at < (scriptLength ?? Infinity)
      ? i
      : { ...i, position: { ...i.position, at: i.position.at - appended } };

  const visiting = new Set<string>();
  const build = (block: RawBlock): RealFunctionBytecode => {
    if (visiting.has(block.sfi)) throw new BytecodeCaptureError(`SFI ${block.sfi} contains itself`);
    visiting.add(block.sfi);
    const children: Record<string, RealFunctionBytecode> = {};
    block.constantPool.forEach((entry, index) => {
      if (entry.sfi === undefined) return;
      const compiled = after.filter((b) => b.sfi === entry.sfi);
      if (compiled.length === 0) return; // never called, so never compiled
      if (compiled.length > 1) throw new BytecodeCaptureError(`SFI ${entry.sfi} (${entry.text}) was compiled more than once`);
      const child = compiled[0] as RawBlock;
      if (child.descriptor !== entry.text) {
        throw new BytecodeCaptureError(`block at SFI ${entry.sfi} is ${child.descriptor}, expected ${entry.text}`);
      }
      children[String(index)] = build(child);
    });
    visiting.delete(block.sfi);
    return {
      name: block.name,
      header: block.header,
      instructions: appended === 0 ? block.instructions : block.instructions.map(reanchor),
      constantPool: block.constantPool.map((c) => c.text),
      handlerTable: block.handlerTable,
      children,
    };
  };
  return build(root);
}

const MARK = fileURLToPath(new URL("./mark.cjs", import.meta.url));
// The listing of even a small program is ~0.7-1 MB of Node internals.
const LISTING_MAX_BYTES = 32 * 1024 * 1024;

export type CaptureOptions = {
  readonly nodeArgs?: readonly string[];
  /**
   * Exit codes of the recorded run(s). A capture run that ends differently took
   * another path (an exception, an out-of-memory exit), so the functions it never
   * reached would be missing from the tree without any error: that throws instead.
   */
  readonly expectedExitCodes?: readonly number[];
  /** The runner; only tests replace it. */
  readonly run?: RunFn;
};

/**
 * Runs a repo-owned fixture program once more under `--print-bytecode` and
 * returns the bytecode tree of its main script. Throws on any failure.
 */
export function captureBytecode(source: string, lang: "js" | "ts", opts: CaptureOptions = {}): RealFunctionBytecode {
  const run = (opts.run ?? runReal)(source, {
    lang,
    nodeArgs: [
      ...(opts.nodeArgs ?? []),
      // Keep SharedFunctionInfos where they were printed (no compaction) and
      // compiled once (no flushing), so the address walk is unambiguous.
      "--no-compact",
      "--no-flush-bytecode",
      "--print-bytecode",
      `--allow-fs-read=${MARK}`,
      "--require",
      MARK,
    ],
    maxBufferBytes: LISTING_MAX_BYTES,
  });
  const expected = opts.expectedExitCodes;
  if (expected !== undefined && !expected.includes(run.exitCode)) {
    throw new BytecodeCaptureError(
      `the bytecode run exited with ${run.exitCode}, but the recorded run(s) exited with ${expected.join(", ")}: ` +
        `the capture would be partial (stderr: ${run.stderr.slice(0, 500)})`,
    );
  }
  try {
    const scriptLength = source.charCodeAt(0) === 0xfeff ? source.length - 1 : source.length;
    return selectUserBytecode(parseBytecodeListing(run.stdout), scriptLength);
  } catch (e) {
    if (e instanceof BytecodeCaptureError && run.exitCode !== 0) {
      throw new BytecodeCaptureError(`${e.message} (exit code ${run.exitCode}; stderr: ${run.stderr.slice(0, 500)})`);
    }
    throw e;
  }
}
